name: Commit message

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  commit:
    name: Commit changes
    runs-on: ubuntu-latest
#    env:
#      GH_COMMIT_TOKEN: ${{secrets.GH_COMMIT_TOKEN}}

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch commit history so `yarn versions:validate` works
          fetch-depth: 0
          # Use an admin token to push directly to master
          token: ${{ secrets.GH_COMMIT_TOKEN }}

      - run: echo $((1 + $RANDOM % 10)) > random.txt
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.event.head_commit.author.name }} [bot]
          author_email: ${{ github.event.head_commit.author.email }}
          message: "${{ github.event.head_commit.message }} \n\n* 📦 Version bump [skip actions]"
          add: '["random.txt"]'
