name: Deploy Service A

on:
  push:
    branches: []
  workflow_dispatch:


jobs:
  example_job:
    name: Deploy Service A
    runs-on: ubuntu-latest
    environment: development:core
    steps:
      - run: echo "Deployed Development Core"
