name: Deploy Service B

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  example_job:
    name: Deploy Service B
    runs-on: ubuntu-latest
    environment: staging:core
    steps:
      - run: echo "Deployed Staging Core"
