name: Deploy Service A

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  staging-order-consumer:
    name: Staging Order Consumer
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://order-consumer.staging.dev

    steps:
      - run: echo "Deployed Staging Order Consumer"
