name: Deploy Service B

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  example_job:
    name: Deploy Service B
    runs-on: ubuntu-latest
    environment: dev:core:api
    steps:
      - run: echo "Deployed Development Core API"
