name: Deploy Core

on:
  workflow_call:
    inputs:
      api:
        description: 'Deploy API'
        required: false
        type: boolean
        default: true
      consumer:
        description: 'Deploy Consumer'
        type: boolean
        required: false
        default: true
      environment:
        description: 'Environment'
        type: string
        required: false
        default: 'development:core'
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Deploy Core
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo ${{ inputs.api }} ${{ inputs.consumer }} ${{ inputs.environment }}
#      - uses: ./.github/actions/my-action@v1
#        with:
#          username: ${{ inputs.username }}
#          token: ${{ secrets.token }}
