name: Deploy Core

on:
  push:
    branches: [other]
  workflow_dispatch:

jobs:
  production:
    uses: quantum-app/actions-playground/.github/workflows/deploy-core.yml@main
    with:
      environment: 'production:core'
      api: true
      consumer: true
    secrets:
      token: ${{ secrets.TOKEN }}
