name: Deploy Service A

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  example_job:
    name: Deploy Service A
    runs-on: ubuntu-latest
    environment: dev:core:order-queue-consumer
    steps:
      - run: echo "Deployed Development Core Order Queue Consumer"
