name: Deploy Staging Core

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: quantum-app/actions-playground/.github/workflows/deploy-core.yml@main
    with:
      environment: 'production:core'
    secrets:
      token: ${{ secrets.TOKEN }}
